
enum AuthRole {
  """일반사용자"""
  user

  """관리자"""
  manager

  """개발자(전체권한)"""
  developer
}

enum AuthQuestion {
  """가장 좋아하는 음식은?"""
  favorite_food

  """가장 좋아하는 영화는?"""
  favorite_movie

  """가장 좋아하는 운동은?"""
  favorite_sports

  """가장 좋아하는 동물은?"""
  favorite_animal

  """가장 좋아하는 색깔은?"""
  favorite_color

  """가장 좋아하는 숫자는?"""
  favorite_number
}

type User {
  id: ID!
  userId: String!
  name: String!
  roles: [AuthRole!]
  questionForSearch: AuthQuestion!
  answerForSearch: String!
  countFollower: Int!
  countFollowing: Int!
}

type Post {
  id: ID!
  title: String!
  contents: String!
  user: User!
  countLike: Int!
  activeAt: Boolean!
  category: Category
}

input PageOptionInput {
  perPage: Int
  page: Int
  after: String
  order: orderInput
}

input orderInput {
  column: String!
  asc: Boolean!
}

input UsersOptionsInput {
  """해당 아이디가 팔로우 하고 있는 유저들을 필터링"""
  followingId: String

  """해당 아이디를 팔로우 하고 있는 유저들을 필터링"""
  followerId: String
  likePostId: String
}

type userPaginate {
  totalCount: Int!
  nodes: [User!]!
  pageInfo: PageInfo!
}

type PageInfo {
  hasNextPage: Boolean!
  startPath: String!
  endPath: String!
}

input PostOptionsInput {
  userId: String
  likeUserId: String
  query: String
  categoryId: String
}

type postPaginate {
  totalCount: Int!
  nodes: [Post!]!
  pageInfo: PageInfo!
}

type Category {
  id: ID!
  label: String!
}

type Query {
  users(pageOptions: PageOptionInput, userOptions: UsersOptionsInput): userPaginate
  getUser: User!
  posts(pageOptions: PageOptionInput, postOptions: PostOptionsInput): postPaginate
  getPost(id: ID!): Post
  categories: [Category!]!
}

type Mutation {
  validateQuestion(userId: String!, questionForSearch: AuthQuestion!, answerForSearch: String!): Boolean
  changePassword(userId: String!, password: String!): Boolean
  signUp(userId: String!, password: String!, name: String!, questionForSearch: AuthQuestion!, answerForSearch: String!): User
  signIn(id: String!, password: String!): String
  deleteUser(id: ID!): Boolean
  toggleLikeUser(targetId: String!, like: Boolean!): Boolean
  toggleLikePost(targetId: String!, like: Boolean!): Boolean
  createPost(title: String!, contents: String!, categoryId: String, activeAt: Boolean): Post!
  updatePost(title: String!, contents: String!, categoryId: String, activeAt: Boolean, postId: ID!): Post!
  deletePost(id: ID!): Boolean!
  updateActiveAt(id: ID!, active: Boolean!): Boolean!
  deleteCategory(id: ID!): Boolean!
  addCategory(label: String!): Boolean!
}
